//! Typed IDs for the GQSEAF native-call ABI. Interpreter control-flow opcodes
//! are separate. Unknown variants identify catalogued calls whose meaning is
//! unresolved; having an ID does not imply that a runtime handler is registered.

macro_rules! native_calls {
    ($($name:ident = $opcode:literal),* $(,)?) => {
        #[repr(u8)]
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub enum NativeCall { $($name = $opcode),* }
        impl NativeCall {
            pub const ALL: &'static [Self] = &[$(Self::$name),*];
            pub const fn from_opcode(opcode: u8) -> Option<Self> {
                match opcode { $($opcode => Some(Self::$name),)* _ => None }
            }
        }
        impl TryFrom<u8> for NativeCall {
            type Error = u8;
            fn try_from(opcode: u8) -> Result<Self, u8> {
                Self::from_opcode(opcode).ok_or(opcode)
            }
        }
        impl From<NativeCall> for u8 {
            fn from(call: NativeCall) -> Self { call as u8 }
        }
    };
}

native_calls! {
    CloseDialogue = 0x0a,
    ExpandMessage = 0x0b,
    ConfigureDialogue = 0x0c,
    Unknown0D = 0x0d,
    CreateSavePoint = 0x0e,
    StartEnemyBattle = 0x0f,
    SpawnActor = 0x10,
    Unknown11 = 0x11,
    DespawnActor = 0x12,
    Unknown13 = 0x13,
    SetActorHeading = 0x14,
    Unknown15 = 0x15,
    MoveActor = 0x16,
    Unknown17 = 0x17,
    MoveActorRelative = 0x18,
    SetActorPosition = 0x19,
    FaceActorAfterMovement = 0x1a,
    DespawnActorAfterMovement = 0x1b,
    GetActorProperty = 0x1c,
    SetActorProperty = 0x1d,
    SetActorPathPoint = 0x1e,
    SpawnEnemyActor = 0x1f,
    ChangeItemCount = 0x20,
    GetItemCount = 0x21,
    SelectPartyMember = 0x22,
    Unknown23 = 0x23,
    AddPartyMember = 0x24,
    RemovePartyMember = 0x25,
    Unknown26 = 0x26,
    FindPartyMember = 0x27,
    SetActorOrientation = 0x28,
    LearnTitle = 0x29,
    GetTitle = 0x2a,
    GetEquippedItem = 0x2b,
    EquipItem = 0x2c,
    UnequipItem = 0x2d,
    LearnTechnique = 0x2e,
    Unknown2F = 0x2f,
    CreateAutomaticEventTrigger = 0x30,
    RemoveAutomaticEventTriggers = 0x31,
    CreateScriptRecord = 0x32,
    RemoveTouchTriggers = 0x33,
    HealParty = 0x34,
    CreateTreasureChest = 0x35,
    IsTreasureOpened = 0x36,
    Unknown37 = 0x37,
    Unknown38 = 0x38,
    SpawnEvent = 0x39,
    ReleaseResourceInstance = 0x3a,
    CreateScriptRecordVariant = 0x3b,
    CreateConfirmedTriangleTrigger = 0x3c,
    CreateConfirmedAreaTrigger = 0x3d,
    RemoveConfirmedTriggers = 0x3e,
    ControlEvent = 0x3f,
    ChangeField = 0x40,
    GetCurrentField = 0x41,
    ConfigureSceneryAnimation = 0x42,
    ClearSceneryAnimation = 0x43,
    Unknown44 = 0x44,
    Unknown45 = 0x45,
    ConfigureRendering = 0x46,
    Unknown47 = 0x47,
    PreloadField = 0x48,
    SetTreasureModel = 0x49,
    ShakeCamera = 0x4a,
    CreateOverlay = 0x4b,
    PlayWorldCinematic = 0x4c,
    SetTriggerMetadata = 0x4d,
    SetTouchTriggerMetadata = 0x4e,
    SetEffectSetting = 0x4f,
    AudioCommand = 0x50,
    SetAudioFade = 0x51,
    PlaySoundSimple = 0x52,
    SetActorAmbientSound = 0x53,
    PlayMovieBlocking = 0x54,
    Unknown55 = 0x55,
    PlayVoice = 0x56,
    CreatePortrait = 0x57,
    LoadPortrait = 0x58,
    WaitMediaPosition = 0x59,
    SetCharacterCostume = 0x5a,
    CreateRingStation = 0x5c,
    ReturnFieldControl = 0x5d,
    ScalePortrait = 0x5e,
    Unknown5F = 0x5f,
    DisableMappedInput = 0x60,
    EnableMappedInput = 0x61,
    IsMappedInputDisabled = 0x62,
    SetTransitionMode = 0x63,
    YieldCommand = 0x64,
    RandomMod = 0x65,
    ShowChoice = 0x66,
    OpenMenu = 0x67,
    SetEventBit = 0x68,
    ClearEventBit = 0x69,
    TestEventBit = 0x6a,
    AddGald = 0x6b,
    IsDebugSession = 0x6c,
    ConfigureSession = 0x6d,
    RumbleController = 0x6e,
    SinDegrees = 0x6f,
    CosDegrees = 0x70,
    Unknown71 = 0x71,
    SetScenarioTimer = 0x72,
    CreateCircleTrigger = 0x73,
    CreateAutomaticCircleTrigger = 0x74,
    CreateConfirmedCircleTrigger = 0x75,
    Unknown76 = 0x76,
    AdjustCharacterAffinity = 0x77,
    ConfigureSorcerersRing = 0x78,
    SetPlayerSize = 0x79,
    RankCharacterAffinity = 0x7a,
    CreateSealedSavePoint = 0x7b,
    ScaledSquareRoot = 0x7c,
    DiscardValue = 0x7d,
    PreloadVoiceBank = 0x7e,
    ReadActorLocalOffset = 0x7f,
    Unknown80 = 0x80,
    ConfigureExGem = 0x81,
    SetDialogueSlotFlag = 0x82,
    PlaySkit = 0x83,
    IsSkitViewed = 0x84,
    Atan2Degrees = 0x85,
    Unknown86 = 0x86,
    Unknown87 = 0x87,
    ForgetRecipe = 0x88,
    SnapshotParty = 0x89,
    Unknown8A = 0x8a,
    Unknown8B = 0x8b,
    Unknown8C = 0x8c,
    SetCharacterName = 0x8d,
    GetScenarioTimerValue = 0x8e,
    Unknown8F = 0x8f,
    ActorExists = 0x90,
    Unknown91 = 0x91,
    Unknown92 = 0x92,
    StageCommand = 0x93,
    StageCommand44 = 0x94,
    CreateTriangleTrigger = 0x95,
    CreateAreaTrigger = 0x96,
    GetEventActor = 0x97,
    ResolveScriptResource = 0x98,
    Unknown99 = 0x99,
    ReleaseScriptResource = 0x9a,
    ConfigureActorAnimation = 0x9b,
    SetActorAnimationFlags = 0x9c,
    Unknown9D = 0x9d,
    IsActorAnimationFinished = 0x9e,
    SetActorAnimationProperty = 0x9f,
    SelectCamera = 0xa0,
    SetCameraProperty = 0xa1,
    GetCameraProperty = 0xa2,
    SetCameraEye = 0xa3,
    SetCameraTransitionValues = 0xa4,
    UnknownA5 = 0xa5,
    SelectActor = 0xa6,
    SetCameraPosition = 0xa7,
    ConfigureCameraParameters = 0xa8,
    ResetCameraBounds = 0xa9,
    UnknownAA = 0xaa,
    ConfigureScreenCopy = 0xab,
    ConfigureCameraAuxiliary = 0xac,
    PlayCameraTrack = 0xad,
    UnknownAE = 0xae,
    StopCameraTrack = 0xaf,
    MeasureActorGeometry = 0xb0,
    WaitActorAnimationFrame = 0xb1,
    SetActorFace = 0xb2,
    SetActorMouth = 0xb3,
    FindActorBodyPart = 0xb4,
    ConfigureActorBoneRotation = 0xb5,
    TurnActorHead = 0xb6,
    AttachActorToMember = 0xb7,
    ReadMappedInput = 0xb8,
    CreateSceneActor = 0xb9,
    SpawnCollisionActor = 0xba,
    SpawnSceneryActor = 0xbb,
    FindActorNode = 0xbc,
    ReadCoordinateRegister = 0xbd,
    ReadActorOffset = 0xbe,
    CreateEffectEmitter = 0xbf,
    ConfigureBattleControl = 0xc0,
    ConfigureActorAttachment = 0xc1,
    ConfigureActorHeadNeck = 0xc2,
    ConfigureActorBoneTranslation = 0xc3,
    ConfigureActorBoneScale = 0xc4,
    SetActorAnimation = 0xc5,
    CreateEnemySource = 0xc6,
    HasRecipe = 0xc7,
    LearnRecipe = 0xc8,
    UnknownC9 = 0xc9,
    RaisePartyMemberLevel = 0xca,
    TransformActorNode = 0xcb,
    ReadActorAttachment = 0xcc,
    StartBattle = 0xcd,
    StageCommand54 = 0xce,
    UnknownCF = 0xcf,
    CreateParticle = 0xd0,
    SetEffectProperty = 0xd1,
    BindEffectTexture = 0xd2,
    CreateEffectObject = 0xd3,
    UnknownD4 = 0xd4,
    UnknownD5 = 0xd5,
    SpawnInteractionActor = 0xd6,
    MotionCommand = 0xd7,
    UnknownD8 = 0xd8,
    GetFieldTicks = 0xd9,
    SetRingTimer = 0xda,
    GetRingTimer = 0xdb,
    MarkTreasureOpened = 0xdc,
    CreateModelParticle = 0xdd,
    SetModelParticleProperty = 0xde,
    GetItemStackLimit = 0xdf,
    PlaySound = 0xe0,
    ConfigureSound = 0xe1,
    PlayActorSound = 0xe2,
    UnknownE3 = 0xe3,
    UnknownE4 = 0xe4,
    SetFieldCountdown = 0xe5,
    GetFieldCountdown = 0xe6,
    UnknownE7 = 0xe7,
    UnknownE8 = 0xe8,
    SelectAudioBank = 0xe9,
    SetSoundReverb = 0xea,
    UnknownEB = 0xeb,
    TriggerExists = 0xec,
    UnknownED = 0xed,
    PreviewSkit = 0xee,
    UnknownF0 = 0xf0,
    SetPortraitTalking = 0xf1,
    UnknownF2 = 0xf2,
    UnknownF3 = 0xf3,
    SetSkitSubtitle = 0xf4,
}
