[package]
name = "resonance-script"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
resonance-battle.workspace = true
anyhow.workspace = true
clap.workspace = true
resonance-events.workspace = true
resonance-model-behavior.workspace = true
symphonia-script-compiler.workspace = true
symphonia-script-tools.workspace = true
