[package]
name = "resonance-battle"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
glam.workspace = true
resonance-content.workspace = true
symphonia-script.workspace = true
symphonia-script-vm.workspace = true

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
symphonia-script-compiler.workspace = true
