# North American Tales of Symphonia, both discs.
# https://wiki.dolphin-emu.org/index.php?title=Tales_of_Symphonia#Reduce_Double_Image
[Gecko]
$Remove Blur
04023C10 4E800020
0403EFA4 4E800020

[Gecko_Enabled]
$Remove Blur
