[package]
name = "resonance-presentation"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
resonance-playback.workspace = true
resonance-audio-device.workspace = true
bevy.workspace = true
resonance-content.workspace = true
resonance-game.workspace = true
symphonia-script.workspace = true
resonance-persistence.workspace = true
anyhow.workspace = true
serde_json.workspace = true
serde.workspace = true
time.workspace = true
resonance-events.workspace = true
sha2.workspace = true
resonance-media.workspace = true
resonance-audio.workspace = true
hound = "3.5"
