[package]
name = "resonance-events"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
symphonia-script.workspace = true
symphonia-script-vm.workspace = true
anyhow.workspace = true
resonance-content.workspace = true

[dev-dependencies]
serde_json.workspace = true
symphonia-script-compiler.workspace = true
